# Generated by Django 5.2.7 on 2025-10-23 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "__first__"),
        ("hotels", "0002_hotel_organization"),
        ("staff", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staff",
            options={
                "ordering": ["organization", "hotel", "role", "user__last_name"],
                "verbose_name": "Staff Member",
                "verbose_name_plural": "Staff Members",
            },
        ),
        migrations.AlterUniqueTogether(
            name="staff",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="staff",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this staff member belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="hotel",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific hotel (optional, null = org-level staff)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff",
                to="hotels.hotel",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="staff",
            unique_together={("organization", "user")},
        ),
    ]
