# Generated by Django 5.0.10 on 2025-10-23 03:14

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("guests", "0002_alter_guest_id_document_number"),
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "confirmation_number",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated unique confirmation code",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked In"),
                            ("checked_out", "Checked Out"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("check_in_date", models.DateField()),
                ("check_out_date", models.DateField()),
                (
                    "nights",
                    models.IntegerField(
                        default=0,
                        help_text="Auto-calculated from check-in/check-out dates",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "adults",
                    models.IntegerField(
                        help_text="Number of adult guests",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "children",
                    models.IntegerField(
                        default=0,
                        help_text="Number of children",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "rate_per_night",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Nightly rate for this reservation",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "total_room_charges",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Auto-calculated: rate_per_night × nights",
                        max_digits=10,
                    ),
                ),
                (
                    "taxes",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "fees",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "extras",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Additional charges (room service, minibar, etc.)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "discounts",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Auto-calculated: room_charges + taxes + fees + extras - discounts",
                        max_digits=10,
                    ),
                ),
                (
                    "deposit_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("direct", "Direct Booking"),
                            ("ota", "Online Travel Agency"),
                            ("gds", "Global Distribution System"),
                            ("walkin", "Walk-in"),
                            ("corporate", "Corporate"),
                            ("voice", "Voice Call"),
                            ("chatbot", "Chatbot"),
                        ],
                        default="direct",
                        max_length=20,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        blank=True,
                        help_text="Specific channel/partner (e.g., Booking.com, Expedia)",
                        max_length=100,
                    ),
                ),
                (
                    "special_requests",
                    models.TextField(
                        blank=True,
                        help_text="Guest special requests (early check-in, late checkout, etc.)",
                        max_length=1000,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about this reservation",
                        max_length=2000,
                    ),
                ),
                ("booked_at", models.DateTimeField(auto_now_add=True)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("checked_out_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True, max_length=500)),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="guests.guest",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="hotels.hotel",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="hotels.room",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="hotels.roomtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reservation",
                "verbose_name_plural": "Reservations",
                "ordering": ["-check_in_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["confirmation_number"],
                        name="reservation_confirm_71004a_idx",
                    ),
                    models.Index(
                        fields=["check_in_date", "check_out_date"],
                        name="reservation_check_i_e85e52_idx",
                    ),
                    models.Index(fields=["status"], name="reservation_status_f1a03a_idx"),
                ],
            },
        ),
    ]
