# Generated by Django 5.0.10 on 2025-10-23 02:09

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Hotel name (3-200 characters)", max_length=200
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier (globally unique)",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        help_text="Brand name (if part of a chain)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("independent", "Independent"),
                            ("chain", "Chain"),
                            ("boutique", "Boutique"),
                        ],
                        help_text="Hotel type",
                        max_length=20,
                    ),
                ),
                (
                    "address",
                    models.JSONField(
                        help_text="Physical address (street, city, state, postal_code, country)"
                    ),
                ),
                (
                    "contact",
                    models.JSONField(
                        help_text="Contact information (phone, email, website)"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        help_text="IANA timezone (e.g., 'America/New_York')",
                        max_length=50,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        help_text="ISO 4217 currency code (e.g., 'USD')", max_length=3
                    ),
                ),
                (
                    "languages",
                    models.JSONField(
                        help_text="Supported languages as ISO 639-1 codes (e.g., ['en', 'es'])"
                    ),
                ),
                (
                    "check_in_time",
                    models.TimeField(help_text="Default check-in time (e.g., '15:00')"),
                ),
                (
                    "check_out_time",
                    models.TimeField(
                        help_text="Default check-out time (e.g., '11:00')"
                    ),
                ),
                (
                    "total_rooms",
                    models.IntegerField(
                        help_text="Total number of rooms in the hotel",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Hotel active status"),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        help_text="Additional hotel settings (booking rules, policies, etc.)",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hotel",
                "verbose_name_plural": "Hotels",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="hotels_hote_slug_ae692c_idx"),
                    models.Index(
                        fields=["is_active"], name="hotels_hote_is_acti_64ad6f_idx"
                    ),
                ],
            },
        ),
    ]
