# Generated by Django 5.2.7 on 2025-10-23 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "__first__"),
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent organization that owns this hotel",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hotels",
                to="core.organization",
            ),
        ),
    ]
