# Generated by Django 5.2.7 on 2025-10-23 21:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0002_populate_default_organization"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NoraContext",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "conversation_history",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of messages with timestamps, roles, content",
                    ),
                ),
                (
                    "preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User preferences learned from interactions",
                    ),
                ),
                (
                    "active_task",
                    models.CharField(
                        blank=True,
                        help_text="Current active task (e.g., 'onboarding', 'creating_booking')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "task_state",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Current state of active task",
                    ),
                ),
                (
                    "recent_actions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Recent actions taken (last 10)",
                    ),
                ),
                (
                    "last_interaction_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last interaction with Nora",
                        null=True,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this context is scoped to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nora_contexts",
                        to="core.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User this context belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nora_contexts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Nora Context",
                "verbose_name_plural": "Nora Contexts",
                "ordering": ["-last_interaction_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "organization"],
                        name="ai_agent_no_user_id_e3dcbb_idx",
                    ),
                    models.Index(
                        fields=["active_task"], name="ai_agent_no_active__e5ccc7_idx"
                    ),
                    models.Index(
                        fields=["last_interaction_at"],
                        name="ai_agent_no_last_in_b51d1f_idx",
                    ),
                ],
                "unique_together": {("user", "organization")},
            },
        ),
    ]
