# Generated by Django 5.2.7 on 2025-10-23 17:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Organization name (e.g., 'Smith Hotel Group')",
                        max_length=200,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier (globally unique)",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("independent", "Independent Hotel"),
                            ("chain", "Hotel Chain/Group"),
                            ("franchise", "Franchise Group"),
                        ],
                        default="independent",
                        help_text="Organization type",
                        max_length=20,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        help_text="Primary contact email for this organization",
                        max_length=254,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Primary contact phone",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Organization active status"
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        help_text="Organization-level settings and preferences",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="core_organi_slug_517c11_idx"),
                    models.Index(
                        fields=["is_active"], name="core_organi_is_acti_9518a1_idx"
                    ),
                ],
            },
        ),
    ]
