# Generated by Django 5.2.7 on 2025-10-23 17:56

from django.db import migrations


def create_default_organization(apps, schema_editor):
    """
    Create a default organization and assign all existing data to it.
    This ensures backward compatibility with existing deployments.
    """
    Organization = apps.get_model("core", "Organization")
    Hotel = apps.get_model("hotels", "Hotel")
    Guest = apps.get_model("guests", "Guest")
    Staff = apps.get_model("staff", "Staff")

    # Create default organization
    default_org, created = Organization.objects.get_or_create(
        slug="default",
        defaults={
            "name": "Default Organization",
            "type": "independent",
            "contact_email": "admin@stayfull.com",
            "is_active": True,
        },
    )

    if created:
        print(f"✓ Created default organization: {default_org.name}")

    # Assign all existing hotels to default org
    hotels_count = Hotel.objects.filter(organization__isnull=True).update(
        organization=default_org
    )
    if hotels_count > 0:
        print(f"✓ Assigned {hotels_count} hotels to default organization")

    # Assign all existing guests to default org
    guests_count = Guest.objects.filter(organization__isnull=True).update(
        organization=default_org
    )
    if guests_count > 0:
        print(f"✓ Assigned {guests_count} guests to default organization")

    # Assign all existing staff to default org
    staff_count = Staff.objects.filter(organization__isnull=True).update(
        organization=default_org
    )
    if staff_count > 0:
        print(f"✓ Assigned {staff_count} staff to default organization")

    print("✓ Data migration complete")


def reverse_migration(apps, schema_editor):
    """Reverse the migration by deleting the default organization"""
    Organization = apps.get_model("core", "Organization")
    Organization.objects.filter(slug="default").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("hotels", "0002_hotel_organization"),
        ("guests", "0003_remove_guest_guests_gues_email_e4fe59_idx_and_more"),
        ("staff", "0002_alter_staff_options_alter_staff_unique_together_and_more"),
    ]

    operations = [
        migrations.RunPython(create_default_organization, reverse_migration),
    ]
