# Generated by Django 5.0.10 on 2025-10-23 02:52

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("guests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="id_document_number",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                help_text="ID document number (encrypted at rest)",
                max_length=255,
                null=True,
            ),
        ),
    ]
