# Generated by Django 5.2.7 on 2025-10-23 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "__first__"),
        ("guests", "0002_alter_guest_id_document_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="guest",
            name="guests_gues_email_e4fe59_idx",
        ),
        migrations.RemoveIndex(
            model_name="guest",
            name="guests_gues_loyalty_4d5cc5_idx",
        ),
        migrations.AddField(
            model_name="guest",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this guest belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="guests",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="guest",
            name="email",
            field=models.EmailField(
                help_text="Email address (unique within organization)", max_length=255
            ),
        ),
        migrations.AlterUniqueTogether(
            name="guest",
            unique_together={("organization", "email")},
        ),
        migrations.AddIndex(
            model_name="guest",
            index=models.Index(
                fields=["organization", "email"], name="guests_gues_organiz_91f122_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guest",
            index=models.Index(
                fields=["organization", "loyalty_tier"],
                name="guests_gues_organiz_b1bff4_idx",
            ),
        ),
    ]
